version: 2.1
job_config: &job_config
  working_directory: ~/code
  docker:
    - image: circleci/openjdk:10.0.2-jdk-sid
  resource_class: xlarge
  environment:
    JVM_OPTS: -Xmx4096m
    GRADLE_MAX_PARALLEL_FORKS: 2
    ANDROID_HOME: /home/circleci/Android

commands:
  run_tests_for_sdks:
    description: "Run tests for specific SDK versions"
    parameters:
      codenames:
        type: string
      versions:
        type: string
    steps:
      - run:
          name: Test << parameters.versions >> (<< parameters.codenames >>)
          command: |
            GRADLE_MAX_PARALLEL_FORKS=2 \
                SKIP_JAVADOC=true \
                ./gradlew test --info --stacktrace --continue \
                --parallel \
                -Drobolectric.enabledSdks=<< parameters.versions >> \
                -Drobolectric.alwaysIncludeVariantMarkersInTestName=true \
                -Dorg.gradle.workers.max=2
      - run:
          name: Collect Test Results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
jobs:
  build:
    << : *job_config
    steps:
      - checkout
      - run:
          name: Calculate Cache Hash
          command: |
            find . \( -name \*.gradle -or -name \*.groovy -or -name \*.sh -or -name \*.rb -or -name circle.yml \) -exec shasum {} \; | sort > .cache-hash
            cat .cache-hash
      - restore_cache:
          key: cache-{{ checksum ".cache-hash" }}
      - run:
          name: Download Dependencies
          command: |
            curl --output ~/android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
            mkdir ~/Android && (cd ~/Android && unzip ~/android-sdk.zip)
            yes | sudo SDKMANAGER_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee' $ANDROID_HOME/tools/bin/sdkmanager --licenses || true
            SDKMANAGER_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee' $ANDROID_HOME/tools/bin/sdkmanager --install 'platforms;android-29' > /dev/null
            ./gradlew --parallel prefetchDependencies
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
            - ~/Android
          key: cache-{{ checksum ".cache-hash" }}
      - run:
          name: Build
          command: SKIP_JAVADOC=true ./gradlew clean assemble testClasses --parallel --stacktrace
      - persist_to_workspace:
          root: ~/code
          paths:
            - ".cache-hash"
            - "[a-zA-Z]*" # not .git

  test_16_17_18:
    << : *job_config
    steps:
      - attach_workspace:
          at: ~/code
      - restore_cache:
          key: cache-{{ checksum ".cache-hash" }}
      - run_tests_for_sdks:
          codenames: JELLY_BEAN
          versions: 16,17,18
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: build/reports
          destination: reports

  test_19_21_22:
    << : *job_config
    steps:
      - attach_workspace:
          at: ~/code
      - restore_cache:
          key: cache-{{ checksum ".cache-hash" }}
      - run_tests_for_sdks:
          codenames: KITKAT/LOLLIPOP
          versions: 19,21,22
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: build/reports
          destination: reports

  test_23_24_25:
    << : *job_config
    steps:
      - attach_workspace:
          at: ~/code
      - restore_cache:
          key: cache-{{ checksum ".cache-hash" }}
      - run_tests_for_sdks:
          codenames: M/N
          versions: 23,24,25
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: build/reports
          destination: reports

  test_26_27:
    << : *job_config
    steps:
      - attach_workspace:
          at: ~/code
      - restore_cache:
          key: cache-{{ checksum ".cache-hash" }}
      - run_tests_for_sdks:
          codenames: O
          versions: 26,27
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: build/reports
          destination: reports

  test_28_29:
    << : *job_config
    steps:
      - attach_workspace:
          at: ~/code
      - restore_cache:
          key: cache-{{ checksum ".cache-hash" }}
      - run_tests_for_sdks:
          codenames: P/Q
          versions: 28,29
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: build/reports
          destination: reports


  finish:
    << : *job_config
    steps:
      - attach_workspace:
          at: ~/code
      - restore_cache:
          key: cache-{{ checksum ".cache-hash" }}
      - run:
          name: Upload Snapshot
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # It'd be really nice to turn this back on again, but https://github.com/robolectric/robolectric/issues/5513
              SKIP_JAVADOC=true \
                ./gradlew upload --no-rebuild
            fi

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test_16_17_18:
          requires:
            - build
      - test_19_21_22:
          requires:
            - build
      - test_23_24_25:
          requires:
            - build
      - test_26_27:
          requires:
            - build
      - test_28_29:
          requires:
            - build
      - finish:
          requires:
            - test_16_17_18
            - test_19_21_22
            - test_23_24_25
            - test_26_27
            - test_28_29
